/*
 *
 * Copyright (C) 2026 Jiri Fajta
 * License: MIT license
 *
 */

package org.Subdivision;

import org.Subdivision.Interface.AddPolygonInterface;

/*
 *
 * This contains the algorithm.
 * 
 */
public class Subdivision{
    private AddPolygonInterface addPolygonInterface;// with this interface you get all polygons generated by this algorithm.

    public void setAddPolygonInterface(AddPolygonInterface addPolygonInterface) {
        this.addPolygonInterface = addPolygonInterface;
    }
    
    public int lerpIntMidpoints(int a, int b) {
        return a + ((b - a) >> 1);
    }
    
    public void initializeRootPolygon(SUBDIVPOLYGON3_16 divpoly) {
        int scale_polygons = 10;// scale triangles to draw visable on screen later.
        int offset_x_polygons = 0;
        int offset_y_polygons = 0;

        //preset:
        divpoly.ndiv = 4;
        divpoly.clipx=0;
        divpoly.clipy=0;
        divpoly.cliph = 1920;
        divpoly.clipv = 1080;

        // start triangle as input. 
        divpoly.r0.v.x = -100;
        divpoly.r0.v.y = -100;
        divpoly.r0.v.z = 0;

        divpoly.r1.v.x = 100;
        divpoly.r1.v.y = -100;
        divpoly.r1.v.z = 0;

        divpoly.r2.v.x = 0;
        divpoly.r2.v.y = 100;
        divpoly.r2.v.z = 0;

        offset_x_polygons = 500;
        offset_y_polygons = 500;

        divpoly.r0.sxy.x = offset_x_polygons - 25 * scale_polygons;
        divpoly.r0.sxy.y = offset_y_polygons - 25 * scale_polygons;

        divpoly.r1.sxy.x = offset_x_polygons + 25 * scale_polygons;
        divpoly.r1.sxy.y = offset_y_polygons - 25 * scale_polygons;

        divpoly.r2.sxy.x = offset_x_polygons + 0 * scale_polygons;
        divpoly.r2.sxy.y = offset_y_polygons + 25 * scale_polygons;

        divpoly.r0.c.r = 255;
        divpoly.r0.c.g = divpoly.r0.c.b = 0;

        divpoly.r1.c.g = 255;
        divpoly.r1.c.r = divpoly.r1.c.b = 0;

        divpoly.r2.c.b = 255;
        divpoly.r2.c.r = divpoly.r2.c.g = 0;

        divpoly.r0.sz = divpoly.r1.sz = divpoly.r2.sz = 5;
    }

    public void start(SUBDIVPOLYGON3_16 divpoly) {
        
        if(addPolygonInterface == null){
             throw new IllegalArgumentException("Subdivision: variable addPolygonInterface cannot be null");
        }
        
        if (!clipTest(divpoly, divpoly.r0.sxy, divpoly.r1.sxy, divpoly.r2.sxy)) {
            return;
        }

        //ROOT
        //System.out.println("\nROOT: " + divpoly.getString());

        if (divpoly.ndiv > divpoly.rvs.length) {
            System.out.println("WARNING: divpoly.ndiv " + divpoly.ndiv + " > divpoly.rv.length " + divpoly.rvs.length + ". So, change to max supported ndiv = " + divpoly.rvs.length);
            divpoly.ndiv = divpoly.rvs.length;
        }
        
        //START DIVISION
        if (divpoly.ndiv > 0) {
            int level = 0;
            divpoly.rvs[level].level = level;

            divpoly.rvs[level].r01 = calculateMidpoints(divpoly.r0, divpoly.r1);//01
            divpoly.rvs[level].r12 = calculateMidpoints(divpoly.r1, divpoly.r2);//12
            divpoly.rvs[level].r20 = calculateMidpoints(divpoly.r2, divpoly.r0);//20
            
            
            //calculateMidpoints3(mid01, mid12, mid20, level);  //MIDDEL
//            divpoly.rvs[level].r0_ptr = divpoly.rvs[level].r01;//copy pointer sub_root
//            divpoly.rvs[level].r1_ptr = divpoly.rvs[level].r12;//copy pointer
//            divpoly.rvs[level].r2_ptr = divpoly.rvs[level].r20;//copy pointer
//            calculateMidpoints3(divpoly, level);
            calculateMidpoints3_continue(divpoly, level, divpoly.rvs[level].r01, divpoly.rvs[level].r12, divpoly.rvs[level].r20);

            //calculateMidpoints3(v_root0, mid01, mid20, level);//LEFT
//            divpoly.rvs[level].r0_ptr = divpoly.r0;//copy pointer sub_root
//            divpoly.rvs[level].r1_ptr = divpoly.rvs[level].r01;//copy pointer
//            divpoly.rvs[level].r2_ptr = divpoly.rvs[level].r20;//copy pointer
//            calculateMidpoints3(divpoly, level);
            calculateMidpoints3_continue(divpoly, level, divpoly.r0, divpoly.rvs[level].r01, divpoly.rvs[level].r20);

            //calculateMidpoints3(v_root1, mid12, mid01, level);//RIGHT
//            divpoly.rvs[level].r0_ptr = divpoly.r1;//copy pointer sub_root
//            divpoly.rvs[level].r1_ptr = divpoly.rvs[level].r12;//copy pointer
//            divpoly.rvs[level].r2_ptr = divpoly.rvs[level].r01;//copy pointer
//            calculateMidpoints3(divpoly, level);
            calculateMidpoints3_continue(divpoly, level, divpoly.r1, divpoly.rvs[level].r12, divpoly.rvs[level].r01);

            //calculateMidpoints3(v_root2, mid20, mid12, level);//DOWN
//            divpoly.rvs[level].r0_ptr = divpoly.r2;//copy pointer sub_root
//            divpoly.rvs[level].r1_ptr = divpoly.rvs[level].r20;//copy pointer
//            divpoly.rvs[level].r2_ptr = divpoly.rvs[level].r12;//copy pointer
//            calculateMidpoints3(divpoly, level);
            calculateMidpoints3_continue(divpoly, level, divpoly.r2, divpoly.rvs[level].r20, divpoly.rvs[level].r12);

        } else {
            addPolygonInterface.addPolygon(divpoly.r0, divpoly.r1, divpoly.r2);
        }//end if (divpoly.ndiv > 0)
    }

    // recursive funcion
    // div = [1-4]
    // level = 0;//[0-3]
    private void calculateMidpoints3(SUBDIVPOLYGON3_16 divpoly, int level) {
        int level_plus_one = level + 1;
        
        // checks the root first.
        if (!clip_not_out_of_bount(divpoly, level)) {
           return;
        }

        // NEXT LEVEL = processing PREVIOUS LEVEL
        if (level_plus_one < divpoly.ndiv) {
            // BRANCH
            divpoly.rvs[level_plus_one].r01 = calculateMidpoints(divpoly.rvs[level].r0_ptr, divpoly.rvs[level].r1_ptr);
            divpoly.rvs[level_plus_one].r12 = calculateMidpoints(divpoly.rvs[level].r1_ptr, divpoly.rvs[level].r2_ptr);
            divpoly.rvs[level_plus_one].r20 = calculateMidpoints(divpoly.rvs[level].r2_ptr, divpoly.rvs[level].r0_ptr);
            divpoly.rvs[level_plus_one].level = level;// level of the midpoints.

            //// next subdevision ////
//            divpoly.rvs[level_plus_one].r0_ptr = divpoly.rvs[level_plus_one].r01;//copy pointer sub_root
//            divpoly.rvs[level_plus_one].r1_ptr = divpoly.rvs[level_plus_one].r12;//copy pointer
//            divpoly.rvs[level_plus_one].r2_ptr = divpoly.rvs[level_plus_one].r20;//copy pointer
//            if (clip_not_out_of_bount(divpoly, level_plus_one)) {
//                //calculateMidpoints3(mid01, mid12, mid20, level_plus_one);  //MIDDEL
//                calculateMidpoints3(divpoly, level_plus_one);
//            }
            calculateMidpoints3_continue(divpoly, level_plus_one, divpoly.rvs[level_plus_one].r01, divpoly.rvs[level_plus_one].r12, divpoly.rvs[level_plus_one].r20);

            
            
//            divpoly.rvs[level_plus_one].r0_ptr = divpoly.rvs[level].r0_ptr;//copy pointer sub_root
//            divpoly.rvs[level_plus_one].r1_ptr = divpoly.rvs[level_plus_one].r01;//copy pointer
//            divpoly.rvs[level_plus_one].r2_ptr = divpoly.rvs[level_plus_one].r20;//copy pointer
//            if (clip_not_out_of_bount(divpoly, level_plus_one)) {
//                //calculateMidpoints3(v_root0, mid01, mid20, level_plus_one);//LEFT
//                calculateMidpoints3(divpoly, level_plus_one);
//            }
            calculateMidpoints3_continue(divpoly, level_plus_one, divpoly.rvs[level].r0_ptr, divpoly.rvs[level_plus_one].r01, divpoly.rvs[level_plus_one].r20);

//            divpoly.rvs[level_plus_one].r0_ptr = divpoly.rvs[level].r1_ptr;//copy pointer sub_root
//            divpoly.rvs[level_plus_one].r1_ptr = divpoly.rvs[level_plus_one].r12;//copy pointer
//            divpoly.rvs[level_plus_one].r2_ptr = divpoly.rvs[level_plus_one].r01;//copy pointer
//            if (clip_not_out_of_bount(divpoly, level_plus_one)) {
//                //calculateMidpoints3(v_root`, md12, mid01, level_plus_one);//RIGHT
//                calculateMidpoints3(divpoly, level_plus_one);
//            }
            calculateMidpoints3_continue(divpoly, level_plus_one,  divpoly.rvs[level].r1_ptr, divpoly.rvs[level_plus_one].r12, divpoly.rvs[level_plus_one].r01);

//            divpoly.rvs[level_plus_one].r0_ptr = divpoly.rvs[level].r2_ptr;//copy pointer sub_root
//            divpoly.rvs[level_plus_one].r1_ptr = divpoly.rvs[level_plus_one].r20;//copy pointer
//            divpoly.rvs[level_plus_one].r2_ptr = divpoly.rvs[level_plus_one].r12;//copy pointer
//            if (clip_not_out_of_bount(divpoly, level_plus_one)) {
//                //calculateMidpoints3(v_root2, mid20, mid12, level_plus_one);//DOWN
//                calculateMidpoints3(divpoly, level_plus_one);
//            }
            calculateMidpoints3_continue(divpoly, level_plus_one, divpoly.rvs[level].r2_ptr, divpoly.rvs[level_plus_one].r20, divpoly.rvs[level_plus_one].r12);
        } else {
            // LEAF
            addPolygonInterface.addPolygon(divpoly.rvs[level].r0_ptr, divpoly.rvs[level].r1_ptr, divpoly.rvs[level].r2_ptr);
        }//end if (level_plus_one < divpoly.ndiv)
    }
    
    // call: calculateMidpoints3_continue(divpoly.rvs[level], divpoly.rvs[level].r2_ptr, divpoly.rvs[level].r20, divpoly.rvs[level].r12);
    private void calculateMidpoints3_continue(SUBDIVPOLYGON3_16 divpoly, int level, RVECTOR r0, RVECTOR r1, RVECTOR r2) {
        divpoly.rvs[level].r0_ptr = r0;//copy pointer sub_root
        divpoly.rvs[level].r1_ptr = r1;//copy pointer
        divpoly.rvs[level].r2_ptr = r2;//copy pointer
        if (clip_not_out_of_bount(divpoly, level)) {// returns true if visible in space.
            calculateMidpoints3(divpoly, level);
        }
    }

    public RVECTOR calculateMidpoints(RVECTOR a, RVECTOR b) {
        RVECTOR mid_out = new RVECTOR();
        mid_out.v.x = lerpIntMidpoints(a.v.x, b.v.x);
        mid_out.v.y = lerpIntMidpoints(a.v.y, b.v.y);
        mid_out.v.z = lerpIntMidpoints(a.v.z, b.v.z);

        mid_out.sxy.x = lerpIntMidpoints(a.sxy.x, b.sxy.x);
        mid_out.sxy.y = lerpIntMidpoints(a.sxy.y, b.sxy.y);

        mid_out.uv[0] = lerpIntMidpoints(a.uv[0], b.uv[0]);
        mid_out.uv[1] = lerpIntMidpoints(a.uv[1], b.uv[1]);

        mid_out.c.r = lerpIntMidpoints(a.c.r, b.c.r);
        mid_out.c.g = lerpIntMidpoints(a.c.g, b.c.g);
        mid_out.c.b = lerpIntMidpoints(a.c.b, b.c.b);
        mid_out.c.a = lerpIntMidpoints(a.c.a, b.c.a);
        
        mid_out.sz = lerpIntMidpoints(a.sz, b.sz);

        return mid_out;
    }

    private boolean clip_not_out_of_bount(SUBDIVPOLYGON3_16 divpoly, int level) {
        return clipTest(divpoly, divpoly.rvs[level].r0_ptr.sxy, divpoly.rvs[level].r1_ptr.sxy, divpoly.rvs[level].r2_ptr.sxy);
    }
    
    //// SCREEN SPACE, is polygon entirely out of screen.
    private boolean clipTest(SUBDIVPOLYGON3_16 divpoly, VECTOR2 v0, VECTOR2 v1, VECTOR2 v2) {
        if(!divpoly.isScreenSpaceClipping()){
            return true;
        }
        long minX, maxX, minY, maxY;

        minX = Math.min(v0.x, Math.min(v1.x, v2.x));
        maxX = Math.max(v0.x, Math.max(v1.x, v2.x));

        minY = Math.min(v0.y, Math.min(v1.y, v2.y));
        maxY = Math.max(v0.y, Math.max(v1.y, v2.y));

        // outside screen?
        if (maxX < divpoly.clipx || minX > divpoly.clipx + divpoly.cliph) {
            return false;
        }
        if (maxY < divpoly.clipy || minY > divpoly.clipy + divpoly.clipv) {
            return false;
        }
        return true; // potentially visible
    }
}
